# (test1 -> test3) -> test2
name: test1
run-name: "Build a release: -> ${{ github.workflow }} (on ${{ github.ref_type }}: ${{ github.ref_name }})"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

  # Allows you to run this workflow manually from the Actions tab (for testing)
  workflow_dispatch:
    inputs:
      target:
        description: "'--last-release' (use the last release) | '<ref>' (commit/tag/branch) | '' (use caller <ref>)"
        required: false
        type: string
        default: "${{ github.ref_name }}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build1:
    uses: ./.github/workflows/test3.yml
    with:
      target: ${{ inputs.target }}
    secrets: inherit

  build2:
    needs: [build1]
    if: needs.build1.result == 'success'

    runs-on:  ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Set github envs for debug
        run: echo 'Set github envs for debug' #'${{ toJSON(needs) }}'
        env:
          GITHUB_JSON: ${{ toJSON(github) }}
          NEEDS_JSON: ${{ toJSON(needs) }}
          ENV_JSON: ${{ toJSON(env) }}
        working-directory: "."

      - name: Display structure of downloaded files
        run: ls -R

      # Download artifact
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: native-executables

      - name: Display structure of downloaded files
        run: ls -R

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # https://github.com/actions/checkout
      - name: "Checkout local repository"
        uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: test
          path: README.md
